name: waapi_client_dart
description: Wwise Authoring API (Waapi) Client for Dart. Provides waapi function calls and topic subscriptions.
version: 2.0.1
repository: https://github.com/tgalpha/waapi_client_dart

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  logger: ^2.3.0
  path: ^1.9.1
  wamp_client: ^0.5.0
  xml: ^6.5.0
